version: 2.1
jobs:
  build:
    docker: 
      - image: mobiledevops/android-sdk-image:29.0.2
    steps:
      - checkout
      - run:
          name: Android Build
          command: ./gradlew clean assembleRelease