version: 2.1
jobs:
  build:
    docker: 
      - image: mobiledevops/android-sdk-image:30.0.3
    steps:
      - checkout
      - run:
          name: Android Build
          command: ./gradlew clean assembleRelease